# Generated by Django 5.0.3 on 2024-04-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_job_description_alter_job_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer')], max_length=255),
        ),
    ]
