# Generated by Django 5.0.3 on 2024-04-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_job_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_employee',
        ),
        migrations.AlterField(
            model_name='job',
            name='department',
            field=models.CharField(choices=[('IT Department', 'IT Department'), ('HR Department', 'Human Resources Department'), ('Finance Department', 'Finance Department')], max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(choices=[('Python Developer', 'Python Developer'), ('Java Developer', 'Java Developer'), ('Data Scientist', 'Data Scientist'), ('AIML Engineer', 'AIML Engineer'), ('Backend Developer', 'Backend Developer'), ('.NET Developer', '.NET Developer'), ('Frontend Developer', 'Frontend Developer'), ('React Developer', 'React Developer'), ('Flutter Developer', 'Flutter Developer'), ('PHP Developer', 'PHP Developer'), ('Django Developer', 'Django Developer')], max_length=255),
        ),
    ]
