# Generated by Django 5.0.3 on 2024-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_user_is_employee_alter_job_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_candidate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_hr',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('HR', 'HR')], default=False, max_length=255),
        ),
    ]
